package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/makifdb/simple-analytics-api/ent"
	"github.com/makifdb/simple-analytics-api/ent/event"
	"github.com/makifdb/simple-analytics-api/graph/model"
)

// Metadata is the resolver for the metadata field.
func (r *eventResolver) Metadata(ctx context.Context, obj *ent.Event) (*string, error) {
	if obj.EventData == nil {
		return nil, nil
	}

	data, err := json.Marshal(obj.EventData)
	if err != nil {
		return nil, err
	}

	strData := string(data)
	return &strData, nil
}

// RecordEvent is the resolver for the recordEvent field.
func (r *mutationResolver) RecordEvent(ctx context.Context, userID uuid.UUID, eventType string, metadata *string) (*ent.Event, error) {

	eventID := uuid.New()                // Generate unique ID for the event
	timestamp := time.Now().UTC()        // Use UTC time
	var metadataMap map[string]any       // To hold the parsed JSON if provided
	var metadataJSONString string = "{}" // Default empty JSON string for DB

	if metadata != nil && *metadata != "" {
		if err := json.Unmarshal([]byte(*metadata), &metadataMap); err != nil {
			return nil, fmt.Errorf("invalid metadata JSON: %w", err)
		}
		metadataJSONString = *metadata
	}

	insertSQL := `INSERT INTO events (event_id, user_id, event_type, timestamp, event_data) VALUES (?, ?, ?, ?, ?)`

	err := r.CliClient.Exec(ctx, insertSQL, eventID, userID, eventType, timestamp, metadataJSONString)
	if err != nil {
		return nil, fmt.Errorf("failed to execute event insert: %w", err)
	}

	createdEvent := &ent.Event{
		EventID:   eventID,
		UserID:    userID,
		EventType: eventType,
		Timestamp: timestamp,
		EventData: metadataMap,
	}

	return createdEvent, nil
}

// EventsByUser is the resolver for the eventsByUser field.
func (r *queryResolver) EventsByUser(ctx context.Context, userID uuid.UUID) ([]*ent.Event, error) {
	events, err := r.EntClient.Event.Query().
		Where(event.UserID(userID)).
		All(ctx)
	if err != nil {
		return nil, err
	}
	return events, nil
}

// AggregateEventsByType is the resolver for the aggregateEventsByType field.
func (r *queryResolver) AggregateEventsByType(ctx context.Context, startTime time.Time, endTime time.Time, eventType string) ([]*model.EventCount, error) {
	type groupResult struct {
		EventType string `json:"event_type"`
		Count     int    `json:"count"`
	}

	var res []groupResult

	// Build the query: filter by time and optionally event type.
	q := r.EntClient.Event.Query().Where(
		event.TimestampGTE(startTime),
		event.TimestampLTE(endTime),
	)
	if eventType != "" {
		q = q.Where(event.EventTypeEQ(eventType))
	}

	// Group by the "event_type" field and aggregate using COUNT.
	if err := q.GroupBy(event.FieldEventType).
		Aggregate(ent.Count()).
		Scan(ctx, &res); err != nil {
		return nil, err
	}

	// Map the results to the GraphQL model.EventCount.
	var counts []*model.EventCount
	for _, r := range res {
		counts = append(counts, &model.EventCount{
			EventType: r.EventType,
			Count:     int32(r.Count),
		})
	}
	return counts, nil
}

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type eventResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
