// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/makifdb/simple-analytics-api/ent/event"
	"github.com/makifdb/simple-analytics-api/ent/predicate"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (eu *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetEventID sets the "event_id" field.
func (eu *EventUpdate) SetEventID(u uuid.UUID) *EventUpdate {
	eu.mutation.SetEventID(u)
	return eu
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (eu *EventUpdate) SetNillableEventID(u *uuid.UUID) *EventUpdate {
	if u != nil {
		eu.SetEventID(*u)
	}
	return eu
}

// SetUserID sets the "user_id" field.
func (eu *EventUpdate) SetUserID(u uuid.UUID) *EventUpdate {
	eu.mutation.SetUserID(u)
	return eu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (eu *EventUpdate) SetNillableUserID(u *uuid.UUID) *EventUpdate {
	if u != nil {
		eu.SetUserID(*u)
	}
	return eu
}

// SetEventType sets the "event_type" field.
func (eu *EventUpdate) SetEventType(s string) *EventUpdate {
	eu.mutation.SetEventType(s)
	return eu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (eu *EventUpdate) SetNillableEventType(s *string) *EventUpdate {
	if s != nil {
		eu.SetEventType(*s)
	}
	return eu
}

// SetTimestamp sets the "timestamp" field.
func (eu *EventUpdate) SetTimestamp(t time.Time) *EventUpdate {
	eu.mutation.SetTimestamp(t)
	return eu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (eu *EventUpdate) SetNillableTimestamp(t *time.Time) *EventUpdate {
	if t != nil {
		eu.SetTimestamp(*t)
	}
	return eu
}

// SetEventData sets the "event_data" field.
func (eu *EventUpdate) SetEventData(m map[string]interface{}) *EventUpdate {
	eu.mutation.SetEventData(m)
	return eu
}

// ClearEventData clears the value of the "event_data" field.
func (eu *EventUpdate) ClearEventData() *EventUpdate {
	eu.mutation.ClearEventData()
	return eu
}

// Mutation returns the EventMutation object of the builder.
func (eu *EventUpdate) Mutation() *EventMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EventUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EventUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EventUpdate) check() error {
	if v, ok := eu.mutation.EventType(); ok {
		if err := event.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "Event.event_type": %w`, err)}
		}
	}
	return nil
}

func (eu *EventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeUUID, value)
	}
	if value, ok := eu.mutation.UserID(); ok {
		_spec.SetField(event.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := eu.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeString, value)
	}
	if value, ok := eu.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := eu.mutation.EventData(); ok {
		_spec.SetField(event.FieldEventData, field.TypeJSON, value)
	}
	if eu.mutation.EventDataCleared() {
		_spec.ClearField(event.FieldEventData, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetEventID sets the "event_id" field.
func (euo *EventUpdateOne) SetEventID(u uuid.UUID) *EventUpdateOne {
	euo.mutation.SetEventID(u)
	return euo
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEventID(u *uuid.UUID) *EventUpdateOne {
	if u != nil {
		euo.SetEventID(*u)
	}
	return euo
}

// SetUserID sets the "user_id" field.
func (euo *EventUpdateOne) SetUserID(u uuid.UUID) *EventUpdateOne {
	euo.mutation.SetUserID(u)
	return euo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableUserID(u *uuid.UUID) *EventUpdateOne {
	if u != nil {
		euo.SetUserID(*u)
	}
	return euo
}

// SetEventType sets the "event_type" field.
func (euo *EventUpdateOne) SetEventType(s string) *EventUpdateOne {
	euo.mutation.SetEventType(s)
	return euo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEventType(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetEventType(*s)
	}
	return euo
}

// SetTimestamp sets the "timestamp" field.
func (euo *EventUpdateOne) SetTimestamp(t time.Time) *EventUpdateOne {
	euo.mutation.SetTimestamp(t)
	return euo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableTimestamp(t *time.Time) *EventUpdateOne {
	if t != nil {
		euo.SetTimestamp(*t)
	}
	return euo
}

// SetEventData sets the "event_data" field.
func (euo *EventUpdateOne) SetEventData(m map[string]interface{}) *EventUpdateOne {
	euo.mutation.SetEventData(m)
	return euo
}

// ClearEventData clears the value of the "event_data" field.
func (euo *EventUpdateOne) ClearEventData() *EventUpdateOne {
	euo.mutation.ClearEventData()
	return euo
}

// Mutation returns the EventMutation object of the builder.
func (euo *EventUpdateOne) Mutation() *EventMutation {
	return euo.mutation
}

// Where appends a list predicates to the EventUpdate builder.
func (euo *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Event entity.
func (euo *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EventUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EventUpdateOne) check() error {
	if v, ok := euo.mutation.EventType(); ok {
		if err := event.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "Event.event_type": %w`, err)}
		}
	}
	return nil
}

func (euo *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeUUID, value)
	}
	if value, ok := euo.mutation.UserID(); ok {
		_spec.SetField(event.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := euo.mutation.EventType(); ok {
		_spec.SetField(event.FieldEventType, field.TypeString, value)
	}
	if value, ok := euo.mutation.Timestamp(); ok {
		_spec.SetField(event.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := euo.mutation.EventData(); ok {
		_spec.SetField(event.FieldEventData, field.TypeJSON, value)
	}
	if euo.mutation.EventDataCleared() {
		_spec.ClearField(event.FieldEventData, field.TypeJSON)
	}
	_node = &Event{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
