// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/makifdb/simple-analytics-api/ent/event"
	"github.com/makifdb/simple-analytics-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescEventID is the schema descriptor for event_id field.
	eventDescEventID := eventFields[0].Descriptor()
	// event.DefaultEventID holds the default value on creation for the event_id field.
	event.DefaultEventID = eventDescEventID.Default.(func() uuid.UUID)
	// eventDescUserID is the schema descriptor for user_id field.
	eventDescUserID := eventFields[1].Descriptor()
	// event.DefaultUserID holds the default value on creation for the user_id field.
	event.DefaultUserID = eventDescUserID.Default.(func() uuid.UUID)
	// eventDescEventType is the schema descriptor for event_type field.
	eventDescEventType := eventFields[2].Descriptor()
	// event.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	event.EventTypeValidator = eventDescEventType.Validators[0].(func(string) error)
	// eventDescTimestamp is the schema descriptor for timestamp field.
	eventDescTimestamp := eventFields[3].Descriptor()
	// event.DefaultTimestamp holds the default value on creation for the timestamp field.
	event.DefaultTimestamp = eventDescTimestamp.Default.(func() time.Time)
}
